ludus:
  - vm_name: "{{ range_id }}-DBZ-DC01"
    hostname: "{{ range_id }}-DC01"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 8
    cpus: 8
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-DBZ-DC02"
    hostname: "{{ range_id }}-DC02"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 8
    cpus: 8
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-DBZ-DC03"
    hostname: "{{ range_id }}-DC03"
    template: win2016-server-x64-template
    vlan: 10
    ip_last_octet: 12
    ram_gb: 8
    cpus: 8
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-DBZ-SRV02"
    hostname: "{{ range_id }}-SRV02"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 22
    ram_gb: 8
    cpus: 8
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-DBZ-SRV03"
    hostname: "{{ range_id }}-SRV03"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 23
    ram_gb: 8
    cpus: 8
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-DBZ-SRV04"
    hostname: "{{ range_id }}-SRV04"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 24
    ram_gb: 8
    cpus: 8
    linux: true
  - vm_name: "{{ range_id }}-DBZ-KALI"
    hostname: "{{ range_id }}-KALI"
    template: kali-x64-desktop-template
    vlan: 10
    ip_last_octet: 99
    ram_gb: 8
    cpus: 8
    linux:
      - packages:
          - kali-linux-default
          - kali-linux-headless
          - dstat
          - ncdu
          - ranger
          - net-tools
          - htop
          - btop
          - tldr
