---
# Setup services for Linux servers
- name: Install necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip
    - curl
    - wget
    - net-tools

# Setup Apache web server if configured
- name: Install Apache
  apt:
    name: apache2
    state: present
  when: services.web is defined and services.web.type == 'apache'

- name: Configure Apache port
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    line: 'Listen {{ services.web.port | default(80) }}'
  when: services.web is defined and services.web.type == 'apache'

- name: Set document root path
  file:
    path: "{{ services.web.document_root | default('/var/www/html') }}"
    state: directory
    mode: '0755'
  when: services.web is defined and services.web.document_root is defined

- name: Enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes
  when: services.web is defined and services.web.type == 'apache'

# Setup MySQL database if configured
- name: Install MySQL
  apt:
    name: 
      - mysql-server
      - python3-mysqldb
    state: present
  when: services.database is defined and services.database.type == 'mysql'

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes
  when: services.database is defined and services.database.type == 'mysql'

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ services.database.root_password }}"
    host_all: yes
    state: present
  when: 
    - services.database is defined 
    - services.database.type == 'mysql' 
    - services.database.root_password is defined 