---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================

- name: Prepare Windows servers set admin password, set hostname
  hosts: domain:!linux_domain
  tags: 'prepare_servers'
  roles:
  - { role: 'settings/admin_password', tags: 'admin_password' }
  - { role: 'settings/hostname', tags: 'hostname' }
  vars:
    local_admin_password: "{{lab.hosts[dict_key].local_admin_password}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"

- name: Prepare Linux servers
  hosts: linux_domain
  become: yes
  tags: 'prepare_linux_servers'
  tasks:
    - name: Set hostname
      hostname:
        name: "{{lab.hosts[dict_key].hostname}}"
      
    - name: Set root password
      user:
        name: root
        password: "{{ lab.hosts[dict_key].local_admin_password | password_hash('sha512') }}"
